#!/bin/bash
process=$1

if [ $# -lt 1 ]; then
cat << ENTER
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    Usage: $0 < PROCESS NAME or ID >
    Kill process!
    Please input somethings:
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
ENTER
fi

if [ $# -ne 0 ]; then
    ps aux|grep $process
    kill `ps -aux|grep $process|awk '{print $2}'`

fi
